### ISSUE TITLE
Using dot, comma and slash as hotkey

### ISSUE THREAD

**Issue by TheMasterDingo** [HikariKnight/hotkeyD#2]
I am trying to use . , and / as hotkeys with ctrl+alt but it does not work. Does the tool support it or am i doing something wrong?

Thanks

**Comment by HikariKnight** [comment]
Hello @TheMasterDingo 
anything not in the list here (in terms of special keys) are not supported
https://github.com/HikariKnight/hotkeyD/blob/master/src/app/hotkeyd/hotkeyswitch.go

you could try use OEM_PERIOD or OEM_COMMA
not sure if they will work though, but worth a try

essentially the file implements all the keycodes from (the documentation for the keycodes library)
https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes

when it comes to / i dont think you will be able to use that
but you can try OEM_2 or OEM_3

**Comment by TheMasterDingo** [comment]
> Hello @TheMasterDingo
> anything not in the list here (in terms of special keys) are not supported
> https://github.com/HikariKnight/hotkeyD/blob/master/src/app/hotkeyd/hotkeyswitch.go
> 
> you could try use OEM_PERIOD or OEM_COMMA
> not sure if they will work though, but worth a try
> 
> essentially the file implements all the keycodes from (the documentation for the keycodes library)
> https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
> 
> when it comes to / i dont think you will be able to use that
> but you can try OEM_2 or OEM_3

Hi,
thanks a lot for the reply, they all work
OEM_COMMA for ,
OEM_PERIOD for .
and OEM_2 for /

i checked that list many times but did not think about using those, was instead using only "COMMA" etc

The program is very simple and yet very effective, i have made a task to launch it on boot and been using it to lower/increase brightness of my 2nd monitor, change default sound device, all this through some mini scripts made with Nirsoft's programs ( i write the command in a .ps1 file then build them as .exe through Win-PS2EXE)
Thanks for creating it, did not find nothing as minimal and simple around

P.s tried to compile it a few times without success, any tips?

**Comment by HikariKnight** [comment]
yeah the OEM keys are symbol keys that are different depending on regional layouts, it is super confusing.
I wrote it primarily to launch a script to ssh into my host machine to detach my mouse and keyboard from my windows VM (which i run this from) as some games require direct mouse and keyboard attached to be playable, and python or autohotkey would obviously trigger anticheat software, hence this small tool was made 😄

I really should update this with build instructions.

there is a build script written in bash since i developed this on linux so i needed to cross compile it to use it in my VM
https://github.com/HikariKnight/hotkeyD/blob/master/src/build

but it should be as simple as running this in the same folder as [hotkeyd.go](https://github.com/HikariKnight/hotkeyD/blob/master/src/app/hotkeyd.go)
`go build -o hotkeyd.exe -v -ldflags -H=windowsgui hotkeyd.go`

If you are using linux or mac as your build machine just run the build script with either `debug` or `release` as the parameter
the debug build just omits the `-ldflags -H=windowsgui` parameters from the build command which hides the terminal window that go programs tend to have.

just make sure you `go get` these dependencies before building
```
go get github.com/MakeNowJust/hotkey
go get github.com/kardianos/osext
go get gopkg.in/ini.v1
go get tawesoft.co.uk/go/dialog
```

**Comment by TheMasterDingo** [comment]
> yeah the OEM keys are symbol keys that are different depending on regional layouts, it is super confusing.
> I wrote it primarily to launch a script to ssh into my host machine to detach my mouse and keyboard from my windows VM (which i run this from) as some games require direct mouse and keyboard attached to be playable, and python or autohotkey would obviously trigger anticheat software, hence this small tool was made 😄
> 
> I really should update this with build instructions.
> 
> there is a build script written in bash since i developed this on linux so i needed to cross compile it to use it in my VM
> https://github.com/HikariKnight/hotkeyD/blob/master/src/build
> 
> but it should be as simple as running this in the same folder as [hotkeyd.go](https://github.com/HikariKnight/hotkeyD/blob/master/src/app/hotkeyd.go)
> `go build -o hotkeyd.exe -v -ldflags -H=windowsgui hotkeyd.go`
> 
> If you are using linux or mac as your build machine just run the build script with either `debug` or `release` as the parameter
> the debug build just omits the `-ldflags -H=windowsgui` parameters from the build command which hides the terminal window that go programs tend to have.
> 
> just make sure you `go get` these dependencies before building
> 
> ```
> go get github.com/MakeNowJust/hotkey
> go get github.com/kardianos/osext
> go get gopkg.in/ini.v1
> go get tawesoft.co.uk/go/dialog
> ```

thank you, will give it a try!
