### ISSUE TITLE
Function keys activate on modifier key. 

### ISSUE THREAD

**Issue by Sokoloft** [HikariKnight/hotkeyD#6]
Hello. 

I recently built a little macro pad that's similar to a stream-deck. It emulates the F13-20 keys by default. 

However using any of the Function keys won't work. It'll activate the command pressing the modifier key. Once the combination is pressed once. I've tried using both "VK_F13" & "VK_F3" on the pad and my keyboard. 

Is this intended? 

Thanks.

**Comment by HikariKnight** [comment]
For the time being every hotkey needs a modifier key from what i remember, i have already bought myself a QMK firmware based keyboard so that i can start experimenting with F13-20 keys myself as i would love to test using these, but without any proper way to test them right now, i will have to wait for my keyboard to arrive (currently the delivery date is anything from december to january+ due to the global shipping situation and component shortage)

If i were to implement a "none" modifier key, i would probably make a blacklist of keys for it so people cannot do silly things like make their T key a hotkey without a modifier as this would effectively prevent the T key from working, if that makes sense. And since i will not make a function without actually testing it properly myself first, i have no choice but wait for my keyboard to be delivered first since i do not trust my golang skills enough to just write the feature and cross my fingers and hope for the best 🙂

**Comment by Sokoloft** [comment]
Hello.

So you shouldn't need to wait for your QMK keyboard to test this. I mentioned I tried using the alt+F3 bind and it did the same thing. I had it set to notepad in my testing. Whenever I would press alt and release. Notepad would open. Without pressing F3 at all. 

```
[test]
Modkeys=alt
Hotkey=VK_F3
Launch=notepad.exe
```

Also. I think it may be a good idea to make the close function a separate .exe. Windows defender and Malwarebytes keep removing hotkeyd.exe now. I've added exceptions now, but figured I'd let you know.

A none modifier would be a great feature, though I'm fine with holding alt if needed.

[This](https://www.partsnotincluded.com/diy-stream-deck-mini-macro-keyboard/) is the little project I found and I've made several. Got enough to make 4 actually. They'll make good xmas presents.

Thank you and happy holidays!

**Comment by HikariKnight** [comment]
hey @Sokoloft thanks for the info, i will make it a separate exe and put a warning the exe sending the keystroke may trigger malwarebytes and antiviruses as a false positive because of it sending alt+f4

I will have a look at the function keys usage later, it might be a limitation built into windows itself (like how the emulated alt+f4 wont close any of the .msc application windows)

**Comment by HikariKnight** [comment]
Update, seems like putting the close window function in its own exe will just trigger more antiviruses with false positives.

**Comment by Sokoloft** [comment]
Oh oof. The issue was because I had VK in front of the binding. Didn't notice at the time.

```
[test]
Modkeys=alt
Hotkey=F13
Launch=notepad.exe
```

Works just fine. 

I've also been uploading my config and batch files I've been making for this in my stuff repo [here](https://github.com/Sokoloft/Stuff/tree/main/hotkeyD_config). Feel free to link it if you'd like so people can use them as examples.

I also downloaded powertoys and rebound some windows specific bindings so now everything is on my alt keys! 
(windows + arrow keys to alt + arrow keys)

Thanks again.

**Comment by HikariKnight** [comment]
> I've also been uploading my config and batch files I've been making for this in my stuff repo [here](https://github.com/Sokoloft/Stuff/tree/main/hotkeyD_config). Feel free to link it if you'd like so people can use them as examples.
> 
> I also downloaded powertoys and rebound some windows specific bindings so now everything is on my alt keys! (windows + arrow keys to alt + arrow keys)
> 
> Thanks again.

you know what, i will actually just slap that in the readme :D
